### ISSUE TITLE
Console WARN Spam:  Icosphere

### ISSUE THREAD

**Issue by ZEROOblivious** [Rosewood-Development/PlayerParticles#94] opened 2022-04-10 11:06 UTC
Greetings,

Server Version: Paper-283 
MC Version: 1.18.2 

We have a WARN/Error spam console when we do an Icosphere when you do these steps:

1. Get into the GUI 
2. Create new Particle
3. Click Dust Color Transition
4.  Click Icosphere
5. Any color will cause the WARN Spam (We've tried all colors including Rainbow) 
6. Below is  the WARN Message that blows up Console. 

![image](https://user-images.githubusercontent.com/32251194/162614979-f4b9c33d-5cd0-4938-9a9f-ea788d8d4a27.png)

`[10.04 06:54:39] [Server] [WARN] [PlayerParticles] Plugin PlayerParticles v8.0 generated an exception while executing task 3488
[10.04 06:54:39] [Server] java.lang.IllegalArgumentExceptionColor parameter outside of expected range: Red Green Blue
[10.04 06:54:39] [Server] 	at java.awt.Color.testColorValueRange(Color.java:312) ~[?:?]
[10.04 06:54:39] [Server] 	at java.awt.Color.<init>(Color.java:397) ~[?:?]
[10.04 06:54:39] [Server] 	at java.awt.Color.<init>(Color.java:371) ~[?:?]
[10.04 06:54:39] [Server] 	at dev.esophose.playerparticles.styles.ParticleStyleIcosphere.getParticles(ParticleStyleIcosphere.java:56) ~[PlayerParticles-8.0.jar:?]
[10.04 06:54:39] [Server] 	at dev.esophose.playerparticles.manager.ParticleManager.getParticlesWithPlayer(ParticleManager.java:278) ~[PlayerParticles-8.0.jar:?]
[10.04 06:54:39] [Server] 	at dev.esophose.playerparticles.manager.ParticleManager.displayParticles(ParticleManager.java:263) ~[PlayerParticles-8.0.jar:?]
[10.04 06:54:39] [Server] 	at dev.esophose.playerparticles.manager.ParticleManager.run(ParticleManager.java:196) ~[PlayerParticles-8.0.jar:?]
[10.04 06:54:39] [Server] 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-283]
[10.04 06:54:39] [Server] 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-283]
[10.04 06:54:39] [Server] 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-283]
[10.04 06:54:39] [Server] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
[10.04 06:54:39] [Server] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
[10.04 06:54:39] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Esophose** [comment] 2022-11-13 07:26
Issue is caused by using either random or random data with icosphere and dust_color_transition, normal colors seem to work fine. Either way, issue resolved in 956626158d635efd42ccaa77481312d2c53771d1. Sorry for that taking so long.

**Closed by Esophose** 2022-11-13 07:26 UTC
Labels: bug
